.TH "Referência do diretório grafalg16.2/trabs/trab3" 3 "Quarta, 21 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório grafalg16.2/trabs/trab3 \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBtrab3\&.h\fP"
.br
.RI "\fIEspecificações das funções a serem implementadas no trabalho 3\&. \fP"
.in -1c
