.TH "Referência do diretório datast" 3 "Quarta, 21 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório datast \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBheap\&.h\fP"
.br
.RI "\fIHeap manipulation functions\&. \fP"
.in -1c
