.TH "Referência do diretório /home/correa/Dropbox/ufrrj/dcc/professores/RicardoCCorrea/grafalg/datast" 3 "Segunda, 31 de Outubro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório /home/correa/Dropbox/ufrrj/dcc/professores/RicardoCCorrea/grafalg/datast \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBheap\&.h\fP"
.br
.RI "\fIHeap manipulation functions\&. \fP"
.in -1c
