.TH "Referência do diretório graph" 3 "Quarta, 21 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório graph \- 
.SH SYNOPSIS
.br
.PP
.SS "Diretórios"

.in +1c
.in -1c
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBgraph\&.h\fP"
.br
.RI "\fIMacros and inline functions of a bitmap implementation of a graph adjacency matrix\&. \fP"
.ti -1c
.RI "arquivo \fBgrinput\&.h\fP"
.br
.RI "\fIFunctions to read a graph from a file in the DIMACS format\&. \fP"
.in -1c
