.TH "Referência do diretório main" 3 "Quarta, 21 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório main \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBtrab_corretor\&.c\fP"
.br
.ti -1c
.RI "arquivo \fBtrab_main\&.h\fP"
.br
.RI "\fIOrientações e gerenciamento dos trabalhos de programação\&. \fP"
.in -1c
