.TH "Referência do diretório graph/direct" 3 "Quarta, 21 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório graph/direct \- 
.SH SYNOPSIS
.br
.PP
.SS "Arquivos"

.in +1c
.ti -1c
.RI "arquivo \fBbitmap\&.h\fP"
.br
.RI "\fIMacros and inline functions for bitwise operations on bitmaps using bit-parallelism\&. \fP"
.in -1c
