.TH "Aresta" 3 "Quarta, 21 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aresta \- \fBAresta\fP de um grafo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trab3\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "\fBVertice\fP \fBv\fP"
.br
.in -1c
.SH "Descrição Detalhada"
.PP 
\fBAresta\fP de um grafo\&. 
.SH "Campos"
.PP 
.SS "\fBVertice\fP Aresta::v"
Uma extremidade desta aresta 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para AB781 Laboratório de Grafos e Algoritmos a partir de seu código-fonte\&.
