.TH "Dist_A" 3 "Domingo, 18 de Setembro de 2016" "Version 2016.2" "AB781 Laboratýrio de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dist_A \- Tipo usado para identificar distância entre arestas de um grafo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trab3\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "\fBDist_V\fP \fBd2\fP"
.br
.in -1c
.SH "Descrição Detalhada"
.PP 
Tipo usado para identificar distância entre arestas de um grafo\&. 
.SH "Campos"
.PP 
.SS "\fBDist_V\fP Dist_A::d2"
Distância de uma extremidade da aresta 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para AB781 Laboratýrio de Grafos e Algoritmos a partir de seu código-fonte\&.
