.TH "/home/correa/Dropbox/ufrrj/dcc/professores/RicardoCCorrea/grafalg/graph/graph.h" 3 "Domingo, 25 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/correa/Dropbox/ufrrj/dcc/professores/RicardoCCorrea/grafalg/graph/graph.h \- Macros and inline functions of a bitmap implementation of a graph adjacency matrix\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <malloc\&.h>\fP
.br
\fC#include <direct/bitmap\&.h>\fP
.br

.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "struct \fBGraph\fP"
.br
.RI "\fIBitmap implementation of a graph adjacency matrix\&. \fP"
.in -1c
.SH "Descrição Detalhada"
.PP 
Macros and inline functions of a bitmap implementation of a graph adjacency matrix\&. 


.PP
\fBData:\fP
.RS 4
Sep 24, 2013 
.RE
.PP
\fBAutor:\fP
.RS 4
Ricardo C\&. Corrêa (correa@ufrrj.br) 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para AB781 Laboratório de Grafos e Algoritmos a partir de seu código-fonte\&.
