.TH "No_Vertice_L" 3 "Domingo, 18 de Setembro de 2016" "Version 2016.2" "AB781 Laboratýrio de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
No_Vertice_L \- Nó de enumeração do conjunto de vértices de um grafo segundo um percurso em largura\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trab3\&.h>\fP
.SH "Descrição Detalhada"
.PP 
Nó de enumeração do conjunto de vértices de um grafo segundo um percurso em largura\&. 

Este tipo precisa ser definido e a função de inspeção \fBalvo_V\fP implementada\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para AB781 Laboratýrio de Grafos e Algoritmos a partir de seu código-fonte\&.
