.TH "Node" 3 "Segunda, 31 de Outubro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- Identification of a member of a bitmap\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bitmap\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "int \fBind\fP"
.br
.RI "\fI\fBNode\fP index in a bitmap\&. \fP"
.ti -1c
.RI "int \fBnelem\fP"
.br
.RI "\fISmallest element that can be in this node of a bitmap\&. \fP"
.ti -1c
.RI "int \fBcur\fP"
.br
.RI "\fICurrent element as an index in this node\&. \fP"
.ti -1c
.RI "\fBNODETYPE\fP * \fBbeg1\fP"
.br
.RI "\fIUsed for backward enumeration\&. \fP"
.ti -1c
.RI "\fBNODETYPE\fP * \fBend1\fP"
.br
.RI "\fIUsed for forward enumeration\&. \fP"
.ti -1c
.RI "\fBNODETYPE\fP * \fBbuf1\fP"
.br
.RI "\fIUsed to enumerate\&. \fP"
.in -1c
.SH "Descrição Detalhada"
.PP 
Identification of a member of a bitmap\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para AB781 Laboratório de Grafos e Algoritmos a partir de seu código-fonte\&.
