.TH "/home/correa/Dropbox/ufrrj/dcc/professores/RicardoCCorrea/grafalg/framework/main/trab_main.h" 3 "Domingo, 25 de Setembro de 2016" "Version 2016.2" "AB781 Laboratório de Grafos e Algoritmos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/correa/Dropbox/ufrrj/dcc/professores/RicardoCCorrea/grafalg/framework/main/trab_main.h \- Orientações e gerenciamento dos trabalhos de programação\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <graph\&.h>\fP
.br
\fC#include <grinput\&.h>\fP
.br

.SH "Descrição Detalhada"
.PP 
Orientações e gerenciamento dos trabalhos de programação\&. 


.PP
\fBData:\fP
.RS 4
Aug 1, 2016 
.RE
.PP
\fBAutor:\fP
.RS 4
Ricardo C\&. Corrêa (correa@ufrrj.br) 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para AB781 Laboratório de Grafos e Algoritmos a partir de seu código-fonte\&.
